version: '3.7'
services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - leden-service
      - team-service
      - wedstrijd-service

  leden-service:
    build: ./leden-service
    ports:
      - "8081:8081"
    environment:
      - DB_URI=mongodb://mongo:27017/leden

  team-service:
    build: ./team-service
    ports:
      - "8082:8082"
    environment:
      - DB_URI=mysql://mysql:3306/teams

  wedstrijd-service:
    build: ./wedstrijd-service
    ports:
      - "8083:8083"
    environment:
      - DB_URI=mysql://mysql:3306/wedstrijden

  mongo:
    image: mongo:latest
    volumes:
      - ./data/db:/data/db

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: wedstrijden
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api-gateway
