apiVersion: apps/v1
kind: Deployment
metadata:
  name: team-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: team-service
  template:
    metadata:
      labels:
        app: team-service
    spec:
      containers:
        - name: team-service
          image: team-service:latest
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: team-service
spec:
  ports:
    - port: 8082
      targetPort: 8082
  selector:
    app: team-service
  type: ClusterIP
